spring:
  application:
    name: api-gateway

server:
  port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
zuul:
  routes:
    spring-user:
      path: user/*
      serviceId: spring-user
    spring-item: item/*

sesecurity:
  oauth2:
    resource:
      user-info-uri:  http://localhost:${server.port}/user
      prefer-token-info: false

